// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/service (interfaces: EventService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/event.go golang-kafka-txn-pipeline/service EventService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	repository "golang-kafka-txn-pipeline/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// ProcessMessage mocks base method.
func (m *MockEventService) ProcessMessage(ctx context.Context, msg repository.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessMessage indicates an expected call of ProcessMessage.
func (mr *MockEventServiceMockRecorder) ProcessMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMessage", reflect.TypeOf((*MockEventService)(nil).ProcessMessage), ctx, msg)
}

// RunConsumer mocks base method.
func (m *MockEventService) RunConsumer(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunConsumer", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunConsumer indicates an expected call of RunConsumer.
func (mr *MockEventServiceMockRecorder) RunConsumer(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunConsumer", reflect.TypeOf((*MockEventService)(nil).RunConsumer), ctx)
}
