// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/service (interfaces: ProducerService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/producer.go golang-kafka-txn-pipeline/service ProducerService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerService is a mock of ProducerService interface.
type MockProducerService struct {
	ctrl     *gomock.Controller
	recorder *MockProducerServiceMockRecorder
	isgomock struct{}
}

// MockProducerServiceMockRecorder is the mock recorder for MockProducerService.
type MockProducerServiceMockRecorder struct {
	mock *MockProducerService
}

// NewMockProducerService creates a new mock instance.
func NewMockProducerService(ctrl *gomock.Controller) *MockProducerService {
	mock := &MockProducerService{ctrl: ctrl}
	mock.recorder = &MockProducerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerService) EXPECT() *MockProducerServiceMockRecorder {
	return m.recorder
}

// GenerateAndPublish mocks base method.
func (m *MockProducerService) GenerateAndPublish(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndPublish", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAndPublish indicates an expected call of GenerateAndPublish.
func (mr *MockProducerServiceMockRecorder) GenerateAndPublish(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndPublish", reflect.TypeOf((*MockProducerService)(nil).GenerateAndPublish), ctx)
}
