// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/service (interfaces: TransactionService)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_service/transaction.go golang-kafka-txn-pipeline/service TransactionService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	service "golang-kafka-txn-pipeline/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
	isgomock struct{}
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockTransactionService) GetBalance(ctx context.Context, accountID string) (*service.AccountBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(*service.AccountBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockTransactionServiceMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockTransactionService)(nil).GetBalance), ctx, accountID)
}

// List mocks base method.
func (m *MockTransactionService) List(ctx context.Context, req service.ListTransactionsRequest) (*service.ListTransactionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*service.ListTransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransactionServiceMockRecorder) List(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransactionService)(nil).List), ctx, req)
}

// ListDeadLetterEvents mocks base method.
func (m *MockTransactionService) ListDeadLetterEvents(ctx context.Context, page, limit int) (*service.ListDeadLetterEventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeadLetterEvents", ctx, page, limit)
	ret0, _ := ret[0].(*service.ListDeadLetterEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeadLetterEvents indicates an expected call of ListDeadLetterEvents.
func (mr *MockTransactionServiceMockRecorder) ListDeadLetterEvents(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeadLetterEvents", reflect.TypeOf((*MockTransactionService)(nil).ListDeadLetterEvents), ctx, page, limit)
}
