// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/repository (interfaces: ConsumerRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/consumer.go golang-kafka-txn-pipeline/repository ConsumerRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-kafka-txn-pipeline/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConsumerRepository is a mock of ConsumerRepository interface.
type MockConsumerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerRepositoryMockRecorder
	isgomock struct{}
}

// MockConsumerRepositoryMockRecorder is the mock recorder for MockConsumerRepository.
type MockConsumerRepositoryMockRecorder struct {
	mock *MockConsumerRepository
}

// NewMockConsumerRepository creates a new mock instance.
func NewMockConsumerRepository(ctrl *gomock.Controller) *MockConsumerRepository {
	mock := &MockConsumerRepository{ctrl: ctrl}
	mock.recorder = &MockConsumerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerRepository) EXPECT() *MockConsumerRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConsumerRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConsumerRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConsumerRepository)(nil).Close))
}

// CommitMessage mocks base method.
func (m *MockConsumerRepository) CommitMessage(ctx context.Context, msg repository.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitMessage indicates an expected call of CommitMessage.
func (mr *MockConsumerRepositoryMockRecorder) CommitMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitMessage", reflect.TypeOf((*MockConsumerRepository)(nil).CommitMessage), ctx, msg)
}

// FetchMessage mocks base method.
func (m *MockConsumerRepository) FetchMessage(ctx context.Context) (repository.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMessage", ctx)
	ret0, _ := ret[0].(repository.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMessage indicates an expected call of FetchMessage.
func (mr *MockConsumerRepositoryMockRecorder) FetchMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMessage", reflect.TypeOf((*MockConsumerRepository)(nil).FetchMessage), ctx)
}
