// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/repository (interfaces: DeadLetterRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/deadletter.go golang-kafka-txn-pipeline/repository DeadLetterRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-kafka-txn-pipeline/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeadLetterRepository is a mock of DeadLetterRepository interface.
type MockDeadLetterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeadLetterRepositoryMockRecorder
	isgomock struct{}
}

// MockDeadLetterRepositoryMockRecorder is the mock recorder for MockDeadLetterRepository.
type MockDeadLetterRepositoryMockRecorder struct {
	mock *MockDeadLetterRepository
}

// NewMockDeadLetterRepository creates a new mock instance.
func NewMockDeadLetterRepository(ctrl *gomock.Controller) *MockDeadLetterRepository {
	mock := &MockDeadLetterRepository{ctrl: ctrl}
	mock.recorder = &MockDeadLetterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadLetterRepository) EXPECT() *MockDeadLetterRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockDeadLetterRepository) Insert(ctx context.Context, event repository.DeadLetterEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockDeadLetterRepositoryMockRecorder) Insert(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDeadLetterRepository)(nil).Insert), ctx, event)
}

// List mocks base method.
func (m *MockDeadLetterRepository) List(ctx context.Context, page, limit int) ([]repository.DeadLetterEvent, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit)
	ret0, _ := ret[0].([]repository.DeadLetterEvent)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDeadLetterRepositoryMockRecorder) List(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeadLetterRepository)(nil).List), ctx, page, limit)
}
