// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/repository (interfaces: ProducerRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/producer.go golang-kafka-txn-pipeline/repository ProducerRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProducerRepository is a mock of ProducerRepository interface.
type MockProducerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProducerRepositoryMockRecorder
	isgomock struct{}
}

// MockProducerRepositoryMockRecorder is the mock recorder for MockProducerRepository.
type MockProducerRepositoryMockRecorder struct {
	mock *MockProducerRepository
}

// NewMockProducerRepository creates a new mock instance.
func NewMockProducerRepository(ctrl *gomock.Controller) *MockProducerRepository {
	mock := &MockProducerRepository{ctrl: ctrl}
	mock.recorder = &MockProducerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerRepository) EXPECT() *MockProducerRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProducerRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerRepository)(nil).Close))
}

// Publish mocks base method.
func (m *MockProducerRepository) Publish(ctx context.Context, key string, value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockProducerRepositoryMockRecorder) Publish(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockProducerRepository)(nil).Publish), ctx, key, value)
}
