// Code generated by MockGen. DO NOT EDIT.
// Source: golang-kafka-txn-pipeline/repository (interfaces: TransactionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/mock_repository/transaction.go golang-kafka-txn-pipeline/repository TransactionRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	repository "golang-kafka-txn-pipeline/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// ApplyEvent mocks base method.
func (m *MockTransactionRepository) ApplyEvent(ctx context.Context, params repository.ApplyEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyEvent", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyEvent indicates an expected call of ApplyEvent.
func (mr *MockTransactionRepositoryMockRecorder) ApplyEvent(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyEvent", reflect.TypeOf((*MockTransactionRepository)(nil).ApplyEvent), ctx, params)
}

// GetAccountBalance mocks base method.
func (m *MockTransactionRepository) GetAccountBalance(ctx context.Context, accountID string) (*repository.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, accountID)
	ret0, _ := ret[0].(*repository.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockTransactionRepositoryMockRecorder) GetAccountBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockTransactionRepository)(nil).GetAccountBalance), ctx, accountID)
}

// ListTransactions mocks base method.
func (m *MockTransactionRepository) ListTransactions(ctx context.Context, params repository.ListTransactionsParams) (repository.ListTransactionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, params)
	ret0, _ := ret[0].(repository.ListTransactionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockTransactionRepositoryMockRecorder) ListTransactions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).ListTransactions), ctx, params)
}
